name: Builder test

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  builder-test-spec:
    strategy:
      fail-fast: false
      matrix:
        license: ['', '/Dep.Tests/docbuilder/.license/license.xml']
    
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Checkout main repository Dep.Tests
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE-data/Dep.Tests
          token: ${{ secrets.READ_PAT }}
          path: Dep.Tests

      - name: Checkout build_tools repository
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/build_tools
          token: ${{ secrets.READ_PAT }}
          path: build_tools

      - name: Checkout office-js-api repository
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/office-js-api
          token: ${{ secrets.READ_PAT }}
          path: office-js-api

      - name: Check release/hotfix branch for build
        run: |
          cd build_tools/scripts/sdkjs_common/jsdoc
          branch=$(python get_latest_branch.py)
          echo "Branch for build: $branch"
          echo "build_branch=$branch" >> $GITHUB_ENV

      - name: Set config to run
        run: 'echo "{ \"branch\": \"${build_branch}\", \"build\": \"latest\" }" > Dep.Tests/docbuilder/config.json'

      - name: Install p7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Run Python script to test
        run: |
          export ONLYOFFICE_BUILDER_LICENSE=${{ github.workspace }}${{ matrix.license }}
          cd Dep.Tests/docbuilder
          python update.py
          python check-docs.py

      - name: Send message to telegram
        if: always()
        shell: bash
        env:
          MESSAGE: |
            Workflow: ${{ github.workflow }}
            Github job: ${{ github.job }}
            Github job status: ${{ job.status }}
            Github job status: ${{ job.status == 'success' && '✅' || job.status == 'failure' && '❌' || '❓' }} - ${{ job.status }}
            
            See action run logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          MESSAGE=$(echo "$MESSAGE" | sed 's/"/\\"/g')
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{
            \"chat_id\": \"${{ secrets.TELEGRAM_TO }}\",
            \"text\": \"$MESSAGE\",
            \"parse_mode\": \"Markdown\",
            \"disable_notification\": true,
            \"disable_web_page_preview\": true
          }"
