name: Puppeteer DocServer test

on:
  workflow_dispatch:

jobs:
  puppeteer-docserver:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Checkout main repository Dep.Tests
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE-data/Dep.Tests
          path: Dep.Tests
          submodules: true
          token: ${{ secrets.READ_PAT }}

      - name: Add reports key to config
        run: |
          node -e "
            const fs = require('fs');
            const filePath = 'Dep.Tests/tools/report_portal/config.json';
            const config = JSON.parse(fs.readFileSync(filePath, 'utf8'));
            
            config.api_key = '${{ secrets.REPORT_KEY }};';
            config.project_name = 'docsserver';
            config.launch_name = 'Github Action ${{ matrix.os }} Chrome';
            
            fs.writeFileSync(filePath, JSON.stringify(config, null, 2));
          "

      - name: Run tests
        run: |
          cd Dep.Tests
          cd puppeteer/engine
          npm install
          python run.py

      - name: Send message to telegram
        if: always()
        shell: bash
        env:
          MESSAGE: |
            Workflow: ${{ github.workflow }}
            Github job: ${{ github.job }}
            Github job status: ${{ job.status }}
            Github job status: ${{ job.status == 'success' && '✅' || job.status == 'failure' && '❌' || '❓' }} - ${{ job.status }}
            
            See action run logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          MESSAGE=$(echo "$MESSAGE" | sed 's/"/\\"/g')
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{
            \"chat_id\": \"${{ secrets.TELEGRAM_TO }}\",
            \"text\": \"$MESSAGE\",
            \"parse_mode\": \"Markdown\",
            \"disable_notification\": true,
            \"disable_web_page_preview\": true
          }"
