name: read json

on:
  workflow_dispatch:

jobs:
  read-json:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: send default message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Workflow: ${{ github.workflow }}
            
            See action run logs: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
            
