name: read json

on:
  workflow_dispatch:

jobs:
  read-json:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Checkout main repository Dep.Tests
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE-data/Dep.Tests
          path: Dep.Tests
          ref: 'test-linux-action'
          token: ${{ secrets.READ_PAT }}

      - name: Init specific submodule
        run: |
          cd Dep.Tests
          git submodule update --init --depth 1 puppeteer/files

      - name: Add reports key to config
        run: |
          node -e "
            const fs = require('fs');
            const filePath = 'Dep.Tests/tools/report_portal/config.json';
            const config = JSON.parse(fs.readFileSync(filePath, 'utf8'));
            
            config.api_key = '${{ secrets.REPORT_KEY }}';
            config.project_name = 'trofim24_personal';
            config.launch_name = 'Github Action linux Chrome';
            
            fs.writeFileSync(filePath, JSON.stringify(config, null, 2));
          "

      - name: Run tests
        run: |
          cd Dep.Tests
          cd puppeteer/engine
          npm install
          sudo apt-get install xvfb x11-apps x11-xkb-utils libx11-6 libx11-xcb1
          Xvfb -ac :99 -screen 0 1280x1024x16 & export DISPLAY=:99
          python run.py tests/desktop/cell/smoke/check_replace_all.js
