name: read json

on:
  workflow_dispatch:

jobs:
  read-json:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout main repository Dep.Tests
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE-data/Dep.Tests
          path: Dep.Tests
          submodules: true
          token: ${{ secrets.READ_PAT }}
      
      - name: Read file
        shell: bash
        run: |
          content="$(cat Dep.Tests/tools/report_portal/config.json)"
          echo "$content"
