name: read json

on:
  workflow_dispatch:

jobs:
  read-json:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main repository Dep.Tests
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE-data/Dep.Tests
          path: Dep.Tests
          token: ${{ secrets.READ_PAT }}
      
      - name: Add reports key to config
        run: |
          node -e "
            const fs = require('fs');
            const filePath = 'Dep.Tests/tools/report_portal/config.json';
            const config = JSON.parse(fs.readFileSync(filePath, 'utf8'));
            
            config.api_key = '${{ secrets.REPORT_KEY }};';
            config.project_name = 'docsserver';
            config.launch_name = 'Github Action ${{ matrix.os }} Chrome';
            
            fs.writeFileSync(filePath, JSON.stringify(config));
          "

      - name: Print config
        run: cat 'Dep.Tests/tools/report_portal/config.json'
