name: read json

on:
  workflow_dispatch:

jobs:
  read-json:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: First task
        run: |
          echo "Running first task"
          exit 1
      
      - name: send default message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Workflow: ${{ github.workflow }}

            Github job: ${{ github.job }}
            Github job status: ${{ job.status }}
            Github job status: ${{ job.status == 'success' && '✅' || job.status == 'failure' && '❌' || '❓' }} - ${{ job.status }}
            
            See action run logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
